---
ssh_private_keys:
  - ~/.ssh/id_rsa

instance_settings:
    box: "centos/7"
    cpus: 2
    memory: 2048
    disk_size: "40GB"
    network:
      private_network_ip: "192.168.33.10"

shared_folders:
  - src: /home/myuser/projects
    dest: /home/vagrant/projects
    type: virtualbox
