---
- name: install python-pip
  yum:
    name: python-pip
    state: present
- name: "install docker compose v{{ docker_compose_version }}"
  pip:
    name: docker-compose
    version: "{{ docker_compose_version }}"
