---
- name: install packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - gcc
    - gcc-c++
    - make

- name: remove old nodejs and npm
  yum:
    name: "{{ packages }}"
    state: removed
  vars:
    packages:
    - nodejs
    - npm

- name: add nodesource repositories for node.js
  yum:
    name: "https://rpm.nodesource.com/pub_{{ nodejs_version }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present

- name: ensure nodejs is installed
  yum:
    name: nodejs
    state: latest
