---
- name: install node.js {{ nodejs_version }}
  unarchive:
    src: "https://nodejs.org/dist/{{ nodejs_version }}/node-{{ nodejs_version }}-linux-x64.tar.xz"
    dest: /usr/share/
    remote_src: true

- name: create symbolic link
  file:
    src: "/usr/share/node-{{ nodejs_version }}-linux-x64"
    dest: "/usr/share/nodejs"
    state: link

- name: create NODEJS_HOME environment variable
  lineinfile:
    path: /home/vagrant/.bashrc
    line: "export NODEJS_HOME=/usr/share/nodejs"
    state: present

- name: add nodejs to the PATH environment variable
  lineinfile:
    path: /home/vagrant/.bashrc
    line: "export PATH=$PATH:$NODEJS_HOME/bin"
    state: present
