---
- name: add node gpg key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add node repository 1/2
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    state: present

- name: add node repository 2/2
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    state: present
