---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - role: epel-repository
      when: ansible_facts['distribution'] == 'CentOS'
    - role: common
    - role: docker
    - role: docker-compose
    - role: terraform
    - role: awscli
    - role: gradle
    - role: nodejs
    - role: golang
    - role: dart
    - role: ngrok
    - role: minikube
    - role: kubectl
