---
- name: install dart v{{ dart_version }}
  unarchive:
    src: "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ dart_version }}/sdk/dartsdk-linux-x64-release.zip"
    dest: /usr/local/
    remote_src: true

- name: create DART_SDK_HOME environment variable
  lineinfile:
    path: /home/vagrant/.bashrc
    line: "export DART_SDK_HOME=/usr/local/bin/dart-sdk"
    state: present

- name: add dart to the PATH environment variable
  lineinfile:
    path: /home/vagrant/.bashrc
    line: "export PATH=$PATH:$DART_SDK_HOME/bin"
    state: present
